# main repo will be displayed in the header
main_repo_name: foliant-docs/foliant
main_repo_url: https://github.com/foliant-docs/foliant

repo_name: foliant-docs/docs
repo_url: https://github.com/foliant-docs/docs
edit_uri: edit/master/src/
theme:
    name: material
    custom_dir: !path ./theme/
    palette:
        - scheme: default
          primary: "rgba(0, 0, 0, 0.87)"
          accent: light blue
          toggle:
            icon: material/weather-night
            name: Switch to dark mode
        - scheme: slate
          toggle:
            icon: material/weather-sunny
            name: Switch to light mode
    font:
        text: PT Sans
        code: PT Mono
    logo: assets/images/octopus-white.svg
    favicon: assets/images/octopus-black-32.ico
    features:
        - search.suggest
        - search.highlight
        - navigation.top
    icon:
      repo: fontawesome/brands/github-alt
    features:
        - search.suggest
        - search.highlight
        - navigation.top


extra:
    social:
        -   icon: fontawesome/brands/github
            link: https://github.com/foliant-docs/foliant
        -   icon: fontawesome/regular/file-pdf
            link: /docs/assets/foliant-docs.pdf
    analytics:
      provider: google
      property: UA-120535275-2
plugins:
    - tags:
        tags_file: tags.md
    - search:
        lang:
          - en
    - i18n:
        default_language: en
        languages:
            en:
                name: English
                build: true
            ru:
                name: Русский
                build: true
        nav_translations:
            ru:
                Tutorials: Инструкции
                Documenting Databases with Foliant: Документирование баз данных Фолиантом
                Installing and Testing: Установка и тестирование

markdown_extensions:
    - def_list
    - pymdownx.highlight
    - toc:
        permalink: true
    - admonition
    - pymdownx.details
    - pymdownx.superfences
extra_css:
    - 'stylesheets/extra.css'
